spring:
  datasource:
    url: jdbc:mysql://localhost:3306/interview_prep?createDatabaseIfNotExist=true
    username: newuser
    password: 1qaz2wsx@DSMAX
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

